kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  rules:
    - host: "argocd.beetlestone.nz"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
